### ISSUE TITLE
Error when disabling Auras on Player Frame

### ISSUE THREAD

**Issue by hulari** [Wetxius/ShestakUI#11]
Hi, 

I get the below error when disabling the Auras on Player Frame option in the buffs and debuffs section.

`Message: Interface/AddOns/ShestakUI/Modules/Maps/MiniMap.lua:426: attempt to index global 'BuffsAnchor' (a nil value)
Time: Mon Nov 27 12:52:43 2023
Count: 1
Stack: Interface/AddOns/ShestakUI/Modules/Maps/MiniMap.lua:426: attempt to index global 'BuffsAnchor' (a nil value)
[string "@Interface/AddOns/ShestakUI/Modules/Maps/MiniMap.lua"]:426: in main chunk

Locals: T = <table> {
 SkinCheckBox = <function> defined @Interface/AddOns/ShestakUI/Core/API.lua:733
 SkinCheckBoxAtlas = <function> defined @Interface/AddOns/ShestakUI/Core/API.lua:769
 RaidDebuffsReverse = <table> {
 }
 SetFontString = <function> defined @Interface/AddOns/ShestakUI/Modules/UnitFrames/Functions.lua:17
 Scale = <function> defined @Interface/AddOns/ShestakUI/Core/PixelPerfect.lua:25
 class = "DEMONHUNTER"
 RaidBuffs = <table> {
 }
 dummy = <function> defined @Interface/AddOns/ShestakUI/Core/Constants.lua:6
 white_list = <table> {
 }
 SkinHelpBox = <function> defined @Interface/AddOns/ShestakUI/Core/API.lua:1030
 level = 70
 IsFramePositionedLeft = <function> defined @Interface/AddOns/ShestakUI/Core/Functions.lua:208
 ColorPlate = <table> {
 }
 CheckChat = <function> defined @Interface/AddOns/ShestakUI/Core/Functions.lua:47
 ShiftBarUpdate = <function> defined @Interface/AddOns/ShestakUI/Modules/ActionBars/Core.lua:451
 merge = <table> {
 }
 CheckPlayerBuff = <function> defined @Interface/AddOns/ShestakUI/Core/Functions.lua:118
 UpdateManaLevel = <function> defined @Interface/AddOns/ShestakUI/Modules/UnitFrames/Functions.lua:358
 StylePet = <function> defined @Interface/AddOns/ShestakUI/Modules/ActionBars/Style.lua:265
 StyleShift = <function> defined @Interface/AddOns/ShestakUI/Modules/ActionBars/Style.lua:255
 PetBarUpdate = <function> defined @Interface/AddOns/ShestakUI/Modules/ActionBars/Core.lua:488
 SkinIconBorder = <function> defined @Interface/AddOns/ShestakUI/Core/API.lua:1079
 ShortValue = <function> defined @Interface/AddOns/ShestakUI/Core/Functions.lua:15
 OpenItems = <table> {
 }
 DebuffBlackList = <table> {
 }
 CurrentProfile = <function> defined @Interface/AddOns/ShestakUI/Core/Functions.lua:220
 HideSpiral = <function> defined @Interface/AddOns/ShestakUI/Modules/ActionBars/Core.lua:309
 HideAuraFrame = <function> defined @Interface/AddOns/ShestakUI/Modules/UnitFrames/Functions.lua:575
 SetModifiedBackdrop = <function> defined @Interface/AddOns/ShestakUI/Core/API.lua:282
 extraHeight = 16
 PlateBlacklist = <table> {
 }
 CustomCastDelayText = <function> defined @Interface/AddOns/ShestakUI/Modules/UnitFrames/Functions.lua:555
 CreateHealthPrediction = <function> defined @Interface/AddOns/ShestakUI/Modules/UnitFrames/Functions.lua:815
 SkinMaxMinFrame = <function> defined @Interface/AddOns/ShestakUI/Core/API.lua:943
 screenWidth = 2560
 PostUpdateRaidHealth = <function> defined @Interface/AddOns/ShestakUI/Modules/UnitFrames/Functions.lua:138
 CreateAuraWatchIcon = <function> defined @Interface/AddOns/ShestakUI/Modules/UnitFrames/Functions.lua:748
 BuffWhiteList = <table> {
 }
 black_list = <table> {
 }
 PostUpdateHealth = <function> defined @Interface/AddOns/ShestakUI/Modules/UnitFrames/Functions.lua:24
 CustomFilterBoss = <function> defined @Interface/AddOns/ShestakUI/Modules/UnitFrames/Functions.lua:714
 ChatSpamList = <table> {
 }
 UpdateAllElements = <function> defined @Interface/AddOns/ShestakUI/Modules/UnitFrames/Functions.lua:11
 RGBToHex = <function> defined @Interface/AddOns/ShestakUI/Core/Functions.lua:37
 EnemySpells = <table> {
 }
 CanDispel = <table> {
 }
 PostCreateIcon = <function> defined @Interface/AddOns/ShestakUI/Modules/UnitFrames/Functions.lua:589
 UpdateClassMana = <function> defined @Interface/AddOns/ShestakUI/Modules/UnitFrames/Functions.lua:380
 RaidBuffsIgnore = <table> {
 }
 PostUpdatePower = <function> defined @Interface/AddOns/ShestakUI/Modules/UnitFrames/Functions.lua:229
 color = <table> {
 }
 newPatch = true
 screenHeight = 1440
 raid_spells = <table> {
 }
 PostCastStart = <function> defined @Interface/AddOns/Shestak`

**Comment by Wetxius** [comment]
Should be fixed in https://github.com/Wetxius/ShestakUI/commit/599323fe9de00646efd71366c389aa76900a6617
