### ISSUE TITLE
Details Toggle Button

### ISSUE THREAD

**Issue by ardacam** [Wetxius/ShestakUI#16]
It would be nice to add a toggle button for details fitting the ui theme.

**Comment by Wetxius** [comment]
What you mean?

**Comment by ardacam** [comment]
I mean a button to show/hide Details addon which will basically do `/details toggle` function but in ShestakUI style. Kinda like ElvUI bottom panel toggle buttons. Something like this.
![Recording 2023-12-27 at 19 41 26](https://github.com/Wetxius/ShestakUI/assets/21109739/ee7ae672-7a45-4c50-a6eb-6b6ad8dcc855)

**Comment by Wetxius** [comment]
Do you test our damage datatext option in Stats? It show dps text and allow click to show/hide Details window.

**Comment by ardacam** [comment]
Oh yeah that's exactly what i was looking for. Just saw that option. Thank you.
