### ISSUE TITLE
wrong iLvl on upgrade interface

### ISSUE THREAD

**Issue by Wolfeg** [Wetxius/ShestakUI#9]
![image](https://github.com/Wetxius/ShestakUI/assets/4620273/a78e2193-53b6-4a38-91c6-375c20537f2c)

**Comment by Wetxius** [comment]
Что-то мне кажется, что это не наши цифры.

**Comment by Wolfeg** [comment]
попробую отключить отображение уровня и проверить, правда только через недельку

**Comment by Wetxius** [comment]
Наведи в окне персонажа на слот при нажатой кнопке alt. Там будут корректные цифры?
![image](https://github.com/Wetxius/ShestakUI/assets/1249672/c1943de6-5442-46a7-ad96-255267fc94a6)

**Comment by Wolfeg** [comment]
> Наведи в окне персонажа на слот при нажатой кнопке alt. Там будут корректные цифры? ![image](https://user-images.githubusercontent.com/1249672/244436301-c1943de6-5442-46a7-ad96-255267fc94a6.png)

здесь верно отображается. сейчас отключил все аддоны, вначале нету текста в апгрейде, если поводить через альт по слотам в окне персонажа, видимо что то кешируется или хз, после этого появляются цифры уже в окне апгрейда.

**Comment by Wolfeg** [comment]
![image](https://github.com/Wetxius/ShestakUI/assets/4620273/1227c6b0-54cc-47e4-9a83-22772b06704a)
допустим тут идут илвл как у оружия если через альт смотреть список доступных
![image](https://github.com/Wetxius/ShestakUI/assets/4620273/4c795795-b695-4262-9672-b9d71cd741a4)

**Comment by Wetxius** [comment]
https://github.com/Wetxius/ShestakUI/commit/faae3b01db4c34f11f5b575caa97df156e226d1c
Возможный фикс

**Comment by Wolfeg** [comment]
к сожалению больше нету возможности проверить, надеюсь что помогло. возможно позже проверю и если что сообщу
